/**
 * Realistic, CORRECT replies of a sales/booking agent in each of the four languages (what a model writes after a
 * customer message in that language). Used to measure the reply-language guard: it must fire on none of them and
 * on every reply of another language. The Spanish set includes the formal «le/les», English product names and
 * URLs, which are what made an earlier word list fire on ~20% of normal Spanish replies.
 */
export const CATALOG_NAMES = [
    'Case for iPhone 15 with MagSafe', 'Bluetooth Noise Cancelling with ANC for the gym', 'Wireless Charger Stand 15W', 'Smart Watch Series 9',
    'Corte y estilo', 'Color y tratamiento',
];

export const ES: string[] = [
    'Con gusto le ayudo. El Case for iPhone 15 with MagSafe cuesta $89.900 COP y tenemos unidades disponibles.',
    'Le cuento que el Bluetooth Noise Cancelling with ANC for the gym tiene cancelación de ruido y dura hasta treinta horas.',
    'Claro, le puedo ayudar con eso. ¿Para qué día le gustaría agendar su cita de corte y estilo?',
    'Nuestro horario de atención es de lunes a viernes de nueve de la mañana a seis de la tarde.',
    'Le confirmo que el envío a Medellín tarda entre dos y tres días hábiles después de la compra.',
    'Puede ver todos los detalles del producto aquí: https://tienda.ejemplo.com/productos/audifonos-bluetooth-noise-cancelling-with-anc',
    'Sí, tenemos disponibilidad el sábado a las 16:00 para color y tratamiento. ¿Desea que la reserve?',
    'El Smart Watch Series 9 viene en tres colores y tiene garantía de un año con la factura de compra.',
    'Nuestra política de reembolso permite devolver el producto dentro de los treinta días siguientes, con el empaque original.',
    'Hola, buenos días. Soy el asistente de la tienda. ¿En qué le puedo ayudar el día de hoy?',
    'Le recomiendo el Wireless Charger Stand 15W porque carga rápido y es compatible con la mayoría de los teléfonos.',
    'Para continuar necesito su nombre completo y su correo electrónico, por favor.',
    'Gracias por escribirnos. Su pedido ya salió y llegará mañana en la tarde a la dirección que nos indicó.',
    'No tengo ese dato confirmado en este momento. ¿Quiere que le pida a alguien del equipo que lo confirme?',
    'La consulta dura cuarenta y cinco minutos y cuesta $80.000 COP, con pago en el consultorio.',
    'Le informo que la tienda queda en el centro comercial Santafé, local 215, segundo piso.',
    'Con mucho gusto. ¿Prefiere que le envíe el enlace de pago por este mismo chat o por correo?',
    'El Case for iPhone 15 with MagSafe está disponible en negro, azul y rojo, y todos los colores tienen el mismo precio.',
    'Entiendo su molestia y lamento lo ocurrido. Voy a revisar su caso con el equipo para darle una solución pronto.',
    'Sí, aceptamos tarjeta de crédito, débito y transferencia bancaria. Los pagos con tarjeta no tienen recargo.',
    'Tenemos dos horarios libres el domingo: a las 10:00 y a las 11:30. ¿Cuál le queda mejor?',
    'Le comparto el catálogo completo: https://tienda.ejemplo.com/catalogo y también puede escribirnos si necesita ayuda.',
    'El servicio de color y tratamiento incluye lavado, aplicación del tinte y una hidratación profunda al final.',
    'Perfecto, quedó anotado. Le enviaré un recordatorio un día antes de su cita para que no se le olvide.',
    'Lo siento, ese producto está agotado por ahora, pero puedo avisarle cuando vuelva a estar disponible.',
    'Las devoluciones se pueden hacer en cualquier sucursal presentando la factura y el producto sin usar.',
    'Con gusto le explico: el plan básico cuesta $49.900 COP al mes y el plan completo cuesta $99.900 COP al mes.',
    'Estamos ubicados en la carrera 7 con calle 72, en Bogotá, y atendemos también los sábados hasta las tres de la tarde.',
    'Su cita quedó programada para el viernes a las 15:00. Si necesita cambiarla, solo tiene que avisarnos con tiempo.',
    'Entiendo. ¿Le gustaría que le muestre otras opciones parecidas al Bluetooth Noise Cancelling with ANC for the gym?',
    'Puedo ayudarle con eso. ¿Me indica el número de su pedido para revisar el estado del envío?',
    'Claro que sí, con gusto. Le paso los datos de la transferencia y me avisa cuando haya realizado el pago.',
    'Los precios incluyen IVA y el envío es gratis para compras superiores a $150.000 COP en todo el país.',
    'Gracias a usted. Si tiene otra pregunta sobre nuestros servicios, escríbame cuando quiera y le respondo enseguida.',
    'El tiempo de entrega depende de la ciudad: en Bogotá es al día siguiente y en el resto del país es de tres a cinco días.',
    'No contamos con ese servicio, pero sí ofrecemos corte y estilo y color y tratamiento en la misma sede.',
    'Le sugiero el Smart Watch Series 9 si busca algo con monitoreo de salud, y el modelo anterior si prefiere ahorrar.',
    'Por supuesto, puede cancelar su cita sin costo hasta veinticuatro horas antes de la hora programada.',
    'Su solicitud fue registrada con éxito. Recibirá un mensaje de confirmación en cuanto el equipo la revise.',
    'Aquí tiene el enlace para pagar de forma segura: https://pagos.ejemplo.com/p/abc123 y quedo atento a su confirmación.',
    'Sí, el producto tiene garantía de doce meses contra defectos de fabricación, que se hace efectiva con la factura.',
    'Lamentablemente no puedo darle un descuento adicional, pero le puedo ofrecer el envío gratis en este pedido.',
    'Buenas tardes. Con gusto le ayudo a elegir; cuénteme para qué lo va a usar y le recomiendo la mejor opción.',
    'Le resumo su reserva: corte y estilo, el sábado a las 16:00, a nombre de Joaquín Sosa.',
    'Hay dos tallas disponibles, mediana y grande, y las dos están en stock para entrega inmediata en la tienda.',
    'Con gusto le envío la ubicación exacta y las indicaciones para llegar desde la estación más cercana.',
    'Entiendo que necesita una factura electrónica; puede solicitarla respondiendo este mensaje con su documento y correo.',
    'Disculpe la demora en responder. Ya revisé su consulta y le confirmo que el Wireless Charger Stand 15W sí está disponible.',
];

export const PT: string[] = [
    'Com prazer. O Case for iPhone 15 with MagSafe custa R$ 89,90 e temos unidades disponíveis em estoque.',
    'Nossa política de reembolso permite devolver o produto em até trinta dias após a compra, com a embalagem original.',
    'Claro, posso ajudar com isso. Para qual dia você gostaria de agendar o seu corte e estilo?',
    'O nosso horário de atendimento é de segunda a sexta, das nove da manhã às seis da tarde.',
    'Confirmo que a entrega para São Paulo leva de dois a três dias úteis depois da compra.',
    'Você pode ver todos os detalhes do produto aqui: https://loja.exemplo.com/produtos/fone-bluetooth',
    'Sim, temos horário disponível no sábado às 16:00 para coloração e tratamento. Quer que eu reserve?',
    'O Smart Watch Series 9 vem em três cores e tem garantia de um ano com a nota fiscal da compra.',
    'Olá, bom dia. Sou o assistente da loja. Em que posso ajudar você hoje?',
    'Recomendo o Wireless Charger Stand 15W porque carrega rápido e é compatível com a maioria dos celulares.',
    'Para continuar preciso do seu nome completo e do seu e-mail, por favor.',
    'Obrigado por escrever. O seu pedido já saiu e chega amanhã à tarde no endereço que você informou.',
    'Não tenho essa informação confirmada neste momento. Quer que eu peça a alguém da equipe para confirmar?',
    'A consulta dura quarenta e cinco minutos e custa R$ 150,00, com pagamento no consultório.',
    'A loja fica no centro da cidade, no segundo andar do shopping, perto da praça de alimentação.',
    'Com muito prazer. Prefere que eu envie o link de pagamento por este chat ou por e-mail?',
    'O Case for iPhone 15 with MagSafe está disponível em preto, azul e vermelho, todos com o mesmo preço.',
    'Entendo o seu incômodo e lamento o ocorrido. Vou verificar o seu caso com a equipe para encontrar uma solução.',
    'Sim, aceitamos cartão de crédito, débito e transferência. Os pagamentos no cartão não têm acréscimo.',
    'Temos dois horários livres no domingo: às 10:00 e às 11:30. Qual fica melhor para você?',
    'Segue o catálogo completo: https://loja.exemplo.com/catalogo e pode nos escrever se precisar de ajuda.',
    'O serviço de coloração e tratamento inclui lavagem, aplicação da tinta e uma hidratação profunda no final.',
    'Perfeito, ficou anotado. Vou enviar um lembrete um dia antes do seu agendamento para você não esquecer.',
    'Sinto muito, esse produto está esgotado por enquanto, mas posso avisar quando voltar a ficar disponível.',
    'As devoluções podem ser feitas em qualquer loja, com a nota fiscal e o produto sem uso.',
    'O plano básico custa R$ 49,90 por mês e o plano completo custa R$ 99,90 por mês, já com impostos.',
    'Estamos na avenida Paulista, perto do metrô, e também atendemos aos sábados até as três da tarde.',
    'O seu agendamento ficou marcado para sexta-feira às 15:00. Se precisar mudar, é só nos avisar com antecedência.',
    'Entendi. Você gostaria que eu mostrasse outras opções parecidas com o Bluetooth Noise Cancelling with ANC for the gym?',
    'Posso ajudar com isso. Pode me informar o número do pedido para eu verificar o status da entrega?',
    'Claro que sim. Vou passar os dados da transferência e você me avisa quando fizer o pagamento.',
    'Os preços incluem impostos e a entrega é grátis para compras acima de R$ 300,00 em todo o país.',
    'Eu que agradeço. Se tiver outra dúvida sobre os nossos serviços, é só escrever que respondo logo.',
    'O prazo de entrega depende da cidade: em São Paulo é no dia seguinte e no resto do país leva de três a cinco dias.',
    'Não temos esse serviço, mas oferecemos corte e estilo e coloração e tratamento na mesma unidade.',
    'Sugiro o Smart Watch Series 9 se você procura monitoramento de saúde, e o modelo anterior se prefere economizar.',
    'Claro, você pode cancelar o seu agendamento sem custo até vinte e quatro horas antes do horário marcado.',
    'A sua solicitação foi registrada com sucesso. Você vai receber uma mensagem de confirmação assim que a equipe analisar.',
    'Aqui está o link para pagar com segurança: https://pagamentos.exemplo.com/p/abc123 e fico aguardando a sua confirmação.',
    'Sim, o produto tem garantia de doze meses contra defeitos de fabricação, válida com a nota fiscal.',
    'Infelizmente não posso dar um desconto adicional, mas posso oferecer frete grátis neste pedido.',
    'Boa tarde. Com prazer ajudo você a escolher; me conte para que vai usar e eu indico a melhor opção.',
    'Resumo da sua reserva: corte e estilo, no sábado às 16:00, em nome de Joaquim Sousa.',
    'Há dois tamanhos disponíveis, médio e grande, e os dois estão em estoque para retirada imediata na loja.',
    'Com prazer envio a localização exata e as indicações para chegar a partir da estação mais próxima.',
    'Entendi que você precisa de nota fiscal eletrônica; pode solicitar respondendo esta mensagem com o seu documento.',
];

export const EN: string[] = [
    'Happy to help. The Case for iPhone 15 with MagSafe costs $89.99 and we have units available in stock.',
    'Our refund policy allows you to return the product within thirty days of purchase, in its original packaging.',
    'Of course, I can help with that. Which day would you like to book your haircut and styling appointment?',
    'Our opening hours are Monday to Friday, from nine in the morning to six in the evening.',
    'I can confirm that delivery to Miami takes two to three business days after the purchase.',
    'You can see all the details of the product here: https://store.example.com/products/bluetooth-headphones',
    'Yes, we have availability on Saturday at 16:00 for color and treatment. Would you like me to book it?',
    'The Smart Watch Series 9 comes in three colors and has a one-year warranty with your receipt of purchase.',
    'Hello, good morning. I am the store assistant. How can I help you today?',
    'I recommend the Wireless Charger Stand 15W because it charges fast and works with most of the phones.',
    'To continue I need your full name and your email address, please.',
    'Thank you for writing to us. Your order has already shipped and it will arrive tomorrow afternoon at the address you gave us.',
    'I do not have that information confirmed right now. Would you like me to ask someone from the team to confirm it?',
    'The consultation lasts forty-five minutes and costs $80, with payment at the clinic.',
    'The store is located in the city center, on the second floor of the mall, next to the food court.',
    'With pleasure. Would you prefer that I send the payment link in this chat or by email?',
    'The Case for iPhone 15 with MagSafe is available in black, blue and red, and all of them have the same price.',
    'I understand your frustration and I am sorry about what happened. I will review your case with the team to find a solution.',
    'Yes, we accept credit cards, debit cards and bank transfers. Card payments have no extra fee.',
    'We have two free slots on Sunday: at 10:00 and at 11:30. Which one works better for you?',
    'Here is the full catalog: https://store.example.com/catalog and you can write to us if you need any help.',
    'The color and treatment service includes washing, applying the dye and a deep hydration at the end.',
    'Perfect, it is noted. I will send you a reminder one day before your appointment so that you do not forget.',
    'I am sorry, that product is out of stock for now, but I can let you know when it is available again.',
    'Returns can be made at any of our stores, with the receipt and the unused product.',
    'The basic plan costs $49 per month and the complete plan costs $99 per month, taxes included.',
    'We are on Fifth Avenue, close to the subway, and we are also open on Saturdays until three in the afternoon.',
    'Your appointment is scheduled for Friday at 15:00. If you need to change it, just let us know in advance.',
    'Understood. Would you like me to show you other options similar to the Bluetooth Noise Cancelling with ANC for the gym?',
    'I can help with that. Could you tell me your order number so that I can check the status of the delivery?',
    'Of course. I will send you the transfer details and you can let me know when you have made the payment.',
    'Prices include taxes and delivery is free for purchases over $150 anywhere in the country.',
    'You are welcome. If you have any other question about our services, just write to me and I will answer right away.',
    'The delivery time depends on the city: in Miami it is the next day and in the rest of the country it takes three to five days.',
    'We do not offer that service, but we do have haircut and styling and color and treatment at the same location.',
    'I suggest the Smart Watch Series 9 if you are looking for health monitoring, and the previous model if you prefer to save.',
    'Of course, you can cancel your appointment at no cost up to twenty-four hours before the scheduled time.',
    'Your request was registered successfully. You will receive a confirmation message as soon as the team reviews it.',
    'Here is the link to pay securely: https://payments.example.com/p/abc123 and I will be waiting for your confirmation.',
    'Yes, the product has a twelve-month warranty against manufacturing defects, valid with the receipt.',
    'Unfortunately I cannot give you an additional discount, but I can offer free shipping on this order.',
    'Good afternoon. I would be glad to help you choose; tell me what you will use it for and I will suggest the best option.',
    'Here is a summary of your booking: haircut and styling, on Saturday at 16:00, under the name of John Smith.',
    'There are two sizes available, medium and large, and both of them are in stock for immediate pickup at the store.',
    'I will gladly send you the exact location and the directions to get there from the nearest station.',
    'I understand that you need an electronic invoice; you can request it by replying to this message with your document.',
];

export const FR: string[] = [
    'Avec plaisir. Le Case for iPhone 15 with MagSafe coûte 89,90 € et nous avons des unités disponibles en stock.',
    'Notre politique de remboursement permet de retourner le produit dans les trente jours suivant l\'achat, dans son emballage d\'origine.',
    'Bien sûr, je peux vous aider. Pour quel jour souhaitez-vous réserver votre rendez-vous de coupe et coiffage ?',
    'Nos horaires d\'ouverture sont du lundi au vendredi, de neuf heures du matin à dix-huit heures.',
    'Je vous confirme que la livraison à Lyon prend deux à trois jours ouvrables après l\'achat.',
    'Vous pouvez voir tous les détails du produit ici : https://boutique.exemple.com/produits/casque-bluetooth',
    'Oui, nous avons de la disponibilité samedi à 16:00 pour la couleur et le soin. Voulez-vous que je réserve ?',
    'La Smart Watch Series 9 existe en trois couleurs et elle a une garantie d\'un an avec la facture d\'achat.',
    'Bonjour. Je suis l\'assistant de la boutique. Comment puis-je vous aider aujourd\'hui ?',
    'Je vous recommande le Wireless Charger Stand 15W parce qu\'il charge vite et il est compatible avec la plupart des téléphones.',
    'Pour continuer, j\'ai besoin de votre nom complet et de votre adresse e-mail, s\'il vous plaît.',
    'Merci de nous avoir écrit. Votre commande est déjà partie et elle arrivera demain après-midi à l\'adresse que vous nous avez indiquée.',
    'Je n\'ai pas cette information confirmée pour le moment. Souhaitez-vous que je demande à quelqu\'un de l\'équipe de la confirmer ?',
    'La consultation dure quarante-cinq minutes et coûte 80 €, avec paiement au cabinet.',
    'La boutique se trouve au centre-ville, au deuxième étage du centre commercial, près de la zone de restauration.',
    'Avec grand plaisir. Préférez-vous que j\'envoie le lien de paiement dans ce chat ou par e-mail ?',
    'Le Case for iPhone 15 with MagSafe est disponible en noir, bleu et rouge, et tous ont le même prix.',
    'Je comprends votre mécontentement et je suis désolé pour ce qui s\'est passé. Je vais examiner votre cas avec l\'équipe pour trouver une solution.',
    'Oui, nous acceptons les cartes de crédit, les cartes de débit et le virement bancaire. Les paiements par carte n\'ont pas de frais.',
    'Nous avons deux créneaux libres dimanche : à 10:00 et à 11:30. Lequel vous convient le mieux ?',
    'Voici le catalogue complet : https://boutique.exemple.com/catalogue et vous pouvez nous écrire si vous avez besoin d\'aide.',
    'Le service de couleur et soin comprend le lavage, l\'application de la teinture et une hydratation profonde à la fin.',
    'Parfait, c\'est noté. Je vous enverrai un rappel un jour avant votre rendez-vous pour que vous ne l\'oubliiez pas.',
    'Je suis désolé, ce produit est épuisé pour le moment, mais je peux vous prévenir quand il sera de nouveau disponible.',
    'Les retours peuvent se faire dans n\'importe quelle boutique, avec la facture et le produit non utilisé.',
    'Le forfait de base coûte 49 € par mois et le forfait complet coûte 99 € par mois, taxes comprises.',
    'Nous sommes sur l\'avenue de la République, près du métro, et nous sommes aussi ouverts le samedi jusqu\'à quinze heures.',
    'Votre rendez-vous est prévu vendredi à 15:00. Si vous devez le changer, il suffit de nous prévenir à l\'avance.',
    'Compris. Souhaitez-vous que je vous montre d\'autres options semblables au Bluetooth Noise Cancelling with ANC for the gym ?',
    'Je peux vous aider avec cela. Pouvez-vous m\'indiquer votre numéro de commande pour que je vérifie l\'état de la livraison ?',
    'Bien sûr. Je vous envoie les données du virement et vous me prévenez quand vous aurez effectué le paiement.',
    'Les prix incluent les taxes et la livraison est gratuite pour les achats supérieurs à 150 € dans tout le pays.',
    'Je vous en prie. Si vous avez une autre question sur nos services, écrivez-moi et je vous répondrai tout de suite.',
    'Le délai de livraison dépend de la ville : à Lyon c\'est le lendemain et dans le reste du pays il faut trois à cinq jours.',
    'Nous ne proposons pas ce service, mais nous avons coupe et coiffage et couleur et soin dans le même salon.',
    'Je vous suggère la Smart Watch Series 9 si vous cherchez un suivi de santé, et le modèle précédent si vous préférez économiser.',
    'Bien sûr, vous pouvez annuler votre rendez-vous sans frais jusqu\'à vingt-quatre heures avant l\'heure prévue.',
    'Votre demande a été enregistrée avec succès. Vous recevrez un message de confirmation dès que l\'équipe l\'aura examinée.',
    'Voici le lien pour payer en toute sécurité : https://paiements.exemple.com/p/abc123 et j\'attends votre confirmation.',
    'Oui, le produit a une garantie de douze mois contre les défauts de fabrication, valable avec la facture.',
    'Malheureusement je ne peux pas vous accorder de remise supplémentaire, mais je peux vous offrir la livraison gratuite sur cette commande.',
    'Bonsoir. Je vous aide volontiers à choisir ; dites-moi pour quel usage et je vous conseillerai la meilleure option.',
    'Voici le résumé de votre réservation : coupe et coiffage, samedi à 16:00, au nom de Jean Dupont.',
    'Il y a deux tailles disponibles, moyenne et grande, et les deux sont en stock pour un retrait immédiat en boutique.',
    'Je vous envoie volontiers l\'adresse exacte et les indications pour arriver depuis la station la plus proche.',
    'Je comprends que vous avez besoin d\'une facture électronique ; vous pouvez la demander en répondant à ce message avec votre document.',
];

export const BY_LANGUAGE = { es: ES, pt: PT, en: EN, fr: FR } as const;
