const COPY={
    es:{title:'Orden comercial',customer:'Cliente',date:'Fecha',product:'Producto',quantity:'Cantidad',unit:'Precio unitario',total:'Total',notes:'Notas',commercial:'Estado comercial',payment:'Pago del proveedor',unknown:'Desconocido',footer:'Este documento describe el pedido. No es una factura fiscal ni un comprobante de entrega o reembolso.',states:{pending:'Pendiente',confirmed:'Confirmado',paid:'Marcado pagado por el equipo',cancelled:'Cancelado'},payments:{pending:'Pendiente',paid:'Pago verificado',failed:'Fallido',refunded:'Reembolso registrado'}},
    en:{title:'Commercial order',customer:'Customer',date:'Date',product:'Product',quantity:'Quantity',unit:'Unit price',total:'Total',notes:'Notes',commercial:'Commercial status',payment:'Provider payment',unknown:'Unknown',footer:'This document describes the order. It is not a tax invoice or proof of delivery or refund.',states:{pending:'Pending',confirmed:'Confirmed',paid:'Marked paid by the team',cancelled:'Cancelled'},payments:{pending:'Pending',paid:'Payment verified',failed:'Failed',refunded:'Refund recorded'}},
    pt:{title:'Pedido comercial',customer:'Cliente',date:'Data',product:'Produto',quantity:'Quantidade',unit:'Preço unitário',total:'Total',notes:'Observações',commercial:'Estado comercial',payment:'Pagamento do provedor',unknown:'Desconhecido',footer:'Este documento descreve o pedido. Não é uma nota fiscal nem um comprovante de entrega ou reembolso.',states:{pending:'Pendente',confirmed:'Confirmado',paid:'Marcado pago pela equipe',cancelled:'Cancelado'},payments:{pending:'Pendente',paid:'Pagamento verificado',failed:'Falhou',refunded:'Reembolso registrado'}},
    fr:{title:'Commande commerciale',customer:'Client',date:'Date',product:'Produit',quantity:'Quantité',unit:'Prix unitaire',total:'Total',notes:'Notes',commercial:'État commercial',payment:'Paiement du prestataire',unknown:'Inconnu',footer:'Ce document décrit la commande. Ce n’est ni une facture fiscale ni une preuve de livraison ou de remboursement.',states:{pending:'En attente',confirmed:'Confirmée',paid:'Marquée payée par l’équipe',cancelled:'Annulée'},payments:{pending:'En attente',paid:'Paiement vérifié',failed:'Échec',refunded:'Remboursement enregistré'}},
};
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
/** Display only stored facts. No operator status can become a payment certificate. */
export function catalogOrderDocument(businessName:string,order:any,items:any[],language='es'):string{
    const locale=Object.hasOwn(COPY,language)?language as keyof typeof COPY:'es',c=COPY[locale];
    const money=(value:unknown)=>{
        if(!/^[A-Z]{3}$/.test(order.currency||'')||value==null||!Number.isFinite(Number(value)))return c.unknown;
        return escape(new Intl.NumberFormat(locale,{style:'currency',currency:order.currency}).format(Number(value)));
    };
    const date=new Date(order.created_at),dateText=Number.isFinite(date.getTime())?date.toLocaleDateString(locale):c.unknown;
    return `<!DOCTYPE html><html lang="${locale}"><head><meta charset="utf-8"><title>${c.title}</title><style>body{font-family:Arial,sans-serif;margin:32px;color:#17202a}main{max-width:840px;margin:auto}table{border-collapse:collapse;width:100%}td,th{padding:10px;text-align:left;border-bottom:1px solid #ddd}footer{margin-top:32px;color:#555;font-size:13px}h1{font-size:24px}.total{font-size:20px;font-weight:bold;margin-top:24px}@media print{body{margin:12px}}</style></head><body><main>
        <h1>${escape(businessName)}</h1><h2>${c.title} · ${escape(String(order.id).slice(0,8))}</h2><p>${c.date}: ${escape(dateText)}</p><p>${c.customer}: ${escape(order.contact_name||'—')}</p>
        <p>${c.commercial}: ${escape((c.states as Record<string,string>)[order.status]||c.unknown)}</p><p>${c.payment}: ${escape((c.payments as Record<string,string>)[order.payment_status]||c.unknown)}</p>
        <table><thead><tr><th>${c.product}</th><th>${c.quantity}</th><th>${c.unit}</th><th>${c.total}</th></tr></thead><tbody>${items.map(item=>`<tr><td>${escape(item.product_name)}</td><td>${escape(item.quantity)}</td><td>${money(item.unit_price)}</td><td>${money(item.total_price)}</td></tr>`).join('')}</tbody></table>
        <p class="total">${c.total}: ${money(order.total_amount)}</p><p>${c.notes}: ${escape(order.notes||'—')}</p><footer>${c.footer}</footer></main></body></html>`;
}
