import { PaymentProviderName } from '../types/provider-types';
import { PaymentSourceKind } from './provider-capabilities';

/**
 * Contract for providers WITHOUT native subscriptions (Wompi today).
 *
 * These providers know how to tokenize a payment instrument and execute one
 * charge at a time; the billing calendar, the retries and the dunning live in
 * our own recurring engine. Segregated from IPaymentProvider on purpose: a
 * provider implements one, the other, or both, and business code asks the
 * factory for the interface it actually needs instead of calling methods that
 * throw NotImplementedException.
 */

/** Terms the customer must accept before a source can be stored or charged (Wompi habeas data: two separate tokens). */
export interface AcceptanceContract {
    /** Opaque token to echo back on the charge/source creation. Short-lived — never cache it across requests. */
    token: string;
    /** Public URL of the document the customer is accepting. Must be shown in the checkout. */
    permalink: string;
    /** Provider's contract type, e.g. END_USER_POLICY | PERSONAL_DATA_AUTH. */
    type: string;
}

export interface AcceptanceContracts {
    endUserPolicy: AcceptanceContract;
    /**
     * Wompi requires this second, independent consent on both
     * POST /payment_sources and POST /transactions.  Keeping it required in the
     * charging contract prevents an apparently valid source/charge request from
     * being sent without the personal-data authorization.
     */
    personalDataAuth: AcceptanceContract;
}

/** Evidence that the customer accepted the contracts, persisted for audit (never the JWT itself). */
export interface AcceptanceEvidence {
    acceptedAt: Date;
    acceptedIp?: string;
    /** Token identifiers, not the tokens: `jti` and the document hash when the provider exposes them. */
    endUserPolicyJti?: string;
    personalDataAuthJti?: string;
    documentHash?: string;
}

export interface StartPaymentSourceInput {
    tenantId: string;
    kind: PaymentSourceKind;
    /**
     * Single-use token produced CLIENT-SIDE by the provider's widget/SDK.
     * A raw card number must never reach our backend — that would put us in PCI
     * scope and Wompi forbids it outright.
     */
    token: string;
    customerEmail: string;
    acceptance: AcceptanceContracts;
    /** Phone number for wallet sources (Nequi). */
    phoneNumber?: string;
    /** Default statement shown for Bancolombia recurring-account mandates. */
    paymentDescription?: string;
}

export interface PaymentSourceAuthorizationContext {
    /** Token kind determines which `/tokens/:kind/:id` endpoint must be polled. */
    kind: PaymentSourceKind;
    /** Needed when an approved token is finally converted into a payment source. */
    customerEmail: string;
    paymentDescription?: string;
    /** Fresh provider tokens for the same contract versions the user accepted. */
    acceptance?: AcceptanceContracts;
}

export type PaymentSourceStatus = 'pending_auth' | 'available' | 'declined' | 'voided' | 'error';

export interface ProviderPaymentSource {
    /** Provider id, stored as TEXT even when the provider returns an integer. */
    providerSourceId: string;
    kind: PaymentSourceKind;
    status: PaymentSourceStatus;
    /** Card presentation data, when the provider returns it. */
    brand?: string;
    last4?: string;
    expMonth?: number;
    expYear?: number;
    /** Masked phone for wallet sources. */
    phoneMasked?: string;
    /** Set when the customer must authorize out of band (push notification, bank redirect). */
    authorizationUrl?: string;
    /** Provider token id to poll while status is pending_auth. */
    authTokenId?: string;
    rawStatus?: string;
}

export type ChargeStatus = 'pending' | 'approved' | 'declined' | 'voided' | 'error';

export interface ChargeInput {
    /**
     * Idempotency anchor: unique per charge attempt, generated by the engine and
     * stored on billing_charge_attempts BEFORE the request leaves. Retrying with
     * the same reference is how we recover an indeterminate result.
     */
    reference: string;
    amountCents: number;
    currency: string;
    customerEmail: string;
    providerSourceId: string;
    /**
     * What kind of instrument the stored source is. Providers require different
     * fields per method — Wompi rejects a card charge that omits `installments`
     * — so the adapter cannot guess. Defaults to 'card'.
     */
    sourceKind?: PaymentSourceKind;
    /**
     * Card instalments. A subscription charge is always 1: the customer pays the
     * period in full and financing it would change the amount the issuer settles.
     */
    installments?: number;
    /**
     * Card-on-file signalling. true = same amount on a fixed cadence (COF
     * recurring); false = variable amount (stored COF, e.g. a proration).
     * Wrong value here changes how the issuer scores the transaction.
     */
    recurrent: boolean;
    /**
     * Acceptance tokens. Optional because provider docs disagree on whether they
     * are required when charging an existing source — the engine fetches fresh
     * ones anyway (the call is cheap and the JWTs expire).
     */
    acceptance?: AcceptanceContracts;
    /** Payer identity, required by some methods. */
    customerData?: {
        fullName?: string;
        phoneNumber?: string;
        legalId?: string;
        legalIdType?: string;
    };
}

export interface ProviderCharge {
    providerChargeId: string;
    status: ChargeStatus;
    reference: string;
    amountCents: number;
    currency: string;
    /** Provider's own status string, for debugging only. */
    rawStatus?: string;
    /** Decline/error detail as returned by the provider. */
    statusMessage?: string;
    settledAt?: Date;
}

export interface CheckoutLinkInput {
    reference: string;
    amountCents: number;
    currency: string;
    customerEmail: string;
    description: string;
    /** Absolute URL the customer returns to after paying. */
    redirectUrl?: string;
    expiresAt?: Date;
}

export interface ProviderCheckoutLink {
    url: string;
    providerLinkId?: string;
    expiresAt?: Date;
}

export interface IChargingProvider {
    readonly name: PaymentProviderName;

    /**
     * Fetch the acceptance contracts the customer must agree to. Tokens are
     * short-lived JWTs — fetch fresh, never cache across a charge cycle.
     */
    getAcceptanceContracts(): Promise<AcceptanceContracts>;

    /**
     * Turn a client-side token into a reusable payment source. May return
     * `pending_auth` when the customer still has to approve out of band
     * (Nequi push, bank redirect) — poll with pollPaymentSourceAuth.
     */
    startPaymentSource(input: StartPaymentSourceInput): Promise<ProviderPaymentSource>;

    /** Re-read a source whose authorization was still pending. */
    pollPaymentSourceAuth(
        providerSourceId: string,
        authTokenId?: string,
        context?: PaymentSourceAuthorizationContext,
    ): Promise<ProviderPaymentSource>;

    /** Revoke a stored source (customer removed the card, or it went bad). */
    voidPaymentSource(providerSourceId: string): Promise<void>;

    /**
     * Execute one charge against a stored source.
     *
     * IMPORTANT: with asyncSettlement providers this resolves as soon as the
     * provider ACCEPTS the request — status will be 'pending' and the real
     * outcome arrives by webhook or polling. A resolved promise is NOT a
     * successful payment.
     */
    charge(input: ChargeInput): Promise<ProviderCharge>;

    /** Read the current state of a charge (polling path + reconciliation). */
    getCharge(providerChargeId: string): Promise<ProviderCharge>;

    /**
     * Look a charge up by OUR reference. This is the rescue path for an
     * indeterminate result: when a request times out before we learn the
     * provider's charge id, this is the only way to find out whether the money
     * actually moved — without it, retrying risks double-charging.
     */
    getChargeByReference(reference: string): Promise<ProviderCharge | null>;

    /** Reverse a charge before settlement, when the provider supports it (cards only, in Wompi's case). */
    voidCharge?(providerChargeId: string, amountCents?: number): Promise<void>;

    /** Hosted payment link, for methods that cannot be charged unattended. */
    createCheckoutLink(input: CheckoutLinkInput): Promise<ProviderCheckoutLink>;
}
