/**
 * Reproducible R8 configuration for the Expo SDK 54 Groovy template.
 * Keep the SDK's consumer rules for RN/Expo/JNI; never keep entire libraries here.
 */
const fs = require('fs');
const path = require('path');
const { withAppBuildGradle, withDangerousMod, withGradleProperties } = require('@expo/config-plugins');

const RELEASE_PROPERTIES = {
    'android.enableMinifyInReleaseBuilds': 'true',
    'android.enableShrinkResourcesInReleaseBuilds': 'true',
    'android.enableR8.fullMode': 'true',
};

// Stack trace metadata does not prevent shrinking, optimization or obfuscation.
// Native bridge/reflection rules come from the installed libraries' consumer rules.
const DIAGNOSTIC_RULES = `# Generated by withAndroidReleaseOptimization. Do not edit the native copy.
-keepattributes SourceFile,LineNumberTable
`;

function configureReleaseProperties(properties) {
    return [
        ...properties.filter((entry) => entry.type !== 'property'
            || !Object.prototype.hasOwnProperty.call(RELEASE_PROPERTIES, entry.key)),
        ...Object.entries(RELEASE_PROPERTIES).map(([key, value]) => ({ type: 'property', key, value })),
    ];
}

function configureReleaseGradle(buildGradle) {
    if (buildGradle.language !== 'groovy') {
        throw new Error('Android release optimization requires the Expo Groovy template; review this plugin after an SDK upgrade.');
    }
    const { contents } = buildGradle;
    const templateWiring = [
        /findProperty\(['"]android\.enableMinifyInReleaseBuilds['"]\)/,
        /findProperty\(['"]android\.enableShrinkResourcesInReleaseBuilds['"]\)/,
        /\bminifyEnabled\s+enableMinifyInReleaseBuilds\b/,
        /\bshrinkResources\s+enableShrinkResources\.toBoolean\(\)/,
    ];
    const proguardLine = /^[ \t]*proguardFiles[ \t]+getDefaultProguardFile\(['"]proguard-android(?:-optimize)?\.txt['"]\)[^\r\n]*$/gm;
    if (templateWiring.some((pattern) => !pattern.test(contents)) || (contents.match(proguardLine) || []).length !== 1) {
        throw new Error('Android release optimization could not find the expected Expo release configuration; review this plugin after an SDK upgrade.');
    }
    return {
        ...buildGradle,
        contents: contents.replace(proguardLine, (line) => {
            const optimized = line.replace('proguard-android.txt', 'proguard-android-optimize.txt');
            return /['"]parallly-r8\.pro['"]/.test(optimized)
                ? optimized
                : `${optimized}, "parallly-r8.pro"`;
        }),
    };
}

module.exports = function withAndroidReleaseOptimization(config) {
    config = withGradleProperties(config, (cfg) => {
        cfg.modResults = configureReleaseProperties(cfg.modResults);
        return cfg;
    });
    config = withAppBuildGradle(config, (cfg) => {
        cfg.modResults = configureReleaseGradle(cfg.modResults);
        return cfg;
    });
    return withDangerousMod(config, ['android', async (cfg) => {
        await fs.promises.writeFile(
            path.join(cfg.modRequest.platformProjectRoot, 'app', 'parallly-r8.pro'),
            DIAGNOSTIC_RULES,
            'utf8',
        );
        return cfg;
    }]);
};

module.exports.configureReleaseProperties = configureReleaseProperties;
module.exports.configureReleaseGradle = configureReleaseGradle;
module.exports.DIAGNOSTIC_RULES = DIAGNOSTIC_RULES;
